# Environment variables and paths
VENV_PATH = ".\venv"
DATA_PATH = ".\data\physionet2016"
MODELS_PATH = ".\models"

# Quick commands for development
echo "Heart Sound Analyzer - Quick Commands"
echo "======================================"
echo ""
echo "Setup & Environment:"
echo "  python setup.py                    # Run full environment setup"
echo "  .\venv\Scripts\Activate.ps1        # Activate virtual environment"
echo "  pip install -r requirements.txt   # Install dependencies"
echo ""
echo "Development:"
echo "  jupyter notebook                   # Open Jupyter for preprocessing"
echo "  streamlit run app.py              # Start the web app"
echo "  python -m pytest tests/           # Run tests (when available)"
echo ""
echo "Data & Model:"
echo "  ls data\physionet2016\             # Check dataset structure"
echo "  ls models\                         # Check trained models"
echo "  python -c 'import utils; print(\"Utils OK\")'  # Test utilities"
echo ""
echo "Troubleshooting:"
echo "  python --version                   # Check Python version"
echo "  pip list                          # List installed packages"
echo "  streamlit --version               # Check Streamlit installation"